/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { WebComponentNode } from "./components/app-explorer/types";
export namespace Components {
    interface AppExample {
    }
    interface AppExplorer {
    }
    interface AppKnobCssShadowPartList {
        "items": HTMLElement[];
    }
    interface AppKnobCssVariableList {
        "items": string[][];
    }
    interface AppRoot {
    }
    interface AppTabButton {
        "active": boolean;
        /**
          * `true` if the tab button is disabled from selection.
         */
        "disabled": boolean;
        "index": number;
    }
    interface AppTree {
        /**
          * The nested structure of web component element nodes to display in a nested list.
         */
        "node": WebComponentNode;
    }
}
declare global {
    interface HTMLAppExampleElement extends Components.AppExample, HTMLStencilElement {
    }
    var HTMLAppExampleElement: {
        prototype: HTMLAppExampleElement;
        new (): HTMLAppExampleElement;
    };
    interface HTMLAppExplorerElement extends Components.AppExplorer, HTMLStencilElement {
    }
    var HTMLAppExplorerElement: {
        prototype: HTMLAppExplorerElement;
        new (): HTMLAppExplorerElement;
    };
    interface HTMLAppKnobCssShadowPartListElement extends Components.AppKnobCssShadowPartList, HTMLStencilElement {
    }
    var HTMLAppKnobCssShadowPartListElement: {
        prototype: HTMLAppKnobCssShadowPartListElement;
        new (): HTMLAppKnobCssShadowPartListElement;
    };
    interface HTMLAppKnobCssVariableListElement extends Components.AppKnobCssVariableList, HTMLStencilElement {
    }
    var HTMLAppKnobCssVariableListElement: {
        prototype: HTMLAppKnobCssVariableListElement;
        new (): HTMLAppKnobCssVariableListElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLAppTabButtonElement extends Components.AppTabButton, HTMLStencilElement {
    }
    var HTMLAppTabButtonElement: {
        prototype: HTMLAppTabButtonElement;
        new (): HTMLAppTabButtonElement;
    };
    interface HTMLAppTreeElement extends Components.AppTree, HTMLStencilElement {
    }
    var HTMLAppTreeElement: {
        prototype: HTMLAppTreeElement;
        new (): HTMLAppTreeElement;
    };
    interface HTMLElementTagNameMap {
        "app-example": HTMLAppExampleElement;
        "app-explorer": HTMLAppExplorerElement;
        "app-knob-css-shadow-part-list": HTMLAppKnobCssShadowPartListElement;
        "app-knob-css-variable-list": HTMLAppKnobCssVariableListElement;
        "app-root": HTMLAppRootElement;
        "app-tab-button": HTMLAppTabButtonElement;
        "app-tree": HTMLAppTreeElement;
    }
}
declare namespace LocalJSX {
    interface AppExample {
    }
    interface AppExplorer {
    }
    interface AppKnobCssShadowPartList {
        "items"?: HTMLElement[];
    }
    interface AppKnobCssVariableList {
        "items"?: string[][];
        "onVariableChange"?: (event: CustomEvent<{
    name: string;
    value: string;
  }>) => void;
    }
    interface AppRoot {
    }
    interface AppTabButton {
        "active"?: boolean;
        /**
          * `true` if the tab button is disabled from selection.
         */
        "disabled"?: boolean;
        "index"?: number;
        "onTabChange"?: (event: CustomEvent<number>) => void;
    }
    interface AppTree {
        /**
          * The nested structure of web component element nodes to display in a nested list.
         */
        "node"?: WebComponentNode;
        /**
          * The inspect button for a specific element was selected. Emits the `HTMLElement` of the tag selected.
         */
        "onInspect"?: (event: CustomEvent<HTMLElement>) => void;
    }
    interface IntrinsicElements {
        "app-example": AppExample;
        "app-explorer": AppExplorer;
        "app-knob-css-shadow-part-list": AppKnobCssShadowPartList;
        "app-knob-css-variable-list": AppKnobCssVariableList;
        "app-root": AppRoot;
        "app-tab-button": AppTabButton;
        "app-tree": AppTree;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-example": LocalJSX.AppExample & JSXBase.HTMLAttributes<HTMLAppExampleElement>;
            "app-explorer": LocalJSX.AppExplorer & JSXBase.HTMLAttributes<HTMLAppExplorerElement>;
            "app-knob-css-shadow-part-list": LocalJSX.AppKnobCssShadowPartList & JSXBase.HTMLAttributes<HTMLAppKnobCssShadowPartListElement>;
            "app-knob-css-variable-list": LocalJSX.AppKnobCssVariableList & JSXBase.HTMLAttributes<HTMLAppKnobCssVariableListElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "app-tab-button": LocalJSX.AppTabButton & JSXBase.HTMLAttributes<HTMLAppTabButtonElement>;
            "app-tree": LocalJSX.AppTree & JSXBase.HTMLAttributes<HTMLAppTreeElement>;
        }
    }
}
